# Generated by Django 4.1.3 on 2022-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('customer_price', models.IntegerField()),
                ('сost_price', models.IntegerField()),
                ('money_manager', models.IntegerField()),
                ('preparing_for_broadcast', models.IntegerField()),
                ('installation_Dismantling', models.IntegerField()),
                ('broadcasting', models.IntegerField()),
                ('employee_money', models.IntegerField()),
                ('led_screen_rental', models.IntegerField()),
                ('Taxi_transport_costs', models.IntegerField()),
                ('payroll_taxes', models.IntegerField()),
                ('general_running_costs', models.IntegerField()),
                ('Profit', models.IntegerField()),
                ('Profitability', models.IntegerField()),
            ],
        ),
    ]
